### ISSUE TITLE
error compile on alpine

### ISSUE THREAD

**Issue by paulToro** [kaltura/nginx-srt-module#16]
Hi, i am trying to compile the module on an alpine container. I have installed libsrt over apk. accessibel under /usr/lib/libsrt.so.1 (https://alpine.pkgs.org/3.14/alpine-community-x86_64/libsrt-1.4.2-r0.apk.html).
if i am compiling nginx i get the error:
adding module in ../nginx-srt-module
checking for libsrt ... not found
error: srt not found.
what i am doing wrong??

**Comment by erankor** [comment]
The test that is performed during configure, is something like this -
```
# cat /tmp/s.c
#include <srt/srt.h>

int main()
{
        srt_startup();
        return 0;
}
# gcc /tmp/s.c -o /tmp/s -lsrt
#
```
I suggest you will run it manually and check what error you get.

**Comment by paulToro** [comment]
> I think you need the `libsrt-dev` package as well for alpine.

Nice, this solved my issue, Thanks!
