### ISSUE TITLE
SRT Proxy Pass

### ISSUE THREAD

**Issue by quintanaplaca** [kaltura/nginx-srt-module#32]
Hello.

I would just like to confirm that my understanding is correct: I have a scenario where a client has equipment capable of generating an SRT stream in caller mode.

With this module, am I able to configure my server to listen to this stream?

I configured the modules and have it as follows:

```
# Loading modules:
load_module modules/ngx_stream_module.so;
load_module modules/ngx_srt_module.so;
load_module modules/ngx_stream_srt_proxy_module.so;
```

```
# TCP -> SRT proxy
stream {
    server {
        listen 5070;
        srt_proxy_pass srt://127.0.0.1:5071;
    }
}
```

To understand the scenario, I need to be able to create a server to listen to the SRT stream that the other side will send, and then pull that same SRT in caller mode.

Am I capable of this with this module?

Thank you.

**Comment by erankor** [comment]
I didn't understand what you meant by "pull that same SRT in caller mode"... 
But, as stated in the readme, this module can either listen on SRT and proxy to an upstream over TCP, or the opposite - listen on TCP and proxy to an upstream over SRT.

**Comment by quintanaplaca** [comment]
Thank you for your answer, @erankor.
