### ISSUE TITLE
Proxy Protocol to mpegts module

### ISSUE THREAD

**Issue by streamingsystems** [kaltura/nginx-srt-module#34]
Hi,

I am in the process of implementing your (awesome) code in our environment. 

I am going to be using this module to send up to your nginx-mpegts-kmp-module. In that upstream module I will be using the API "connect" to authorize. 

In that upstream module I would like to get the source IP address of the encoder. As such, I will be turning on proxy protocol in this module so the source IP address will be sent up (versus the IP address of the server this module is running on). 

My question is, will that upstream module "just know" that it's proxy protocol that is being sent from this module or do I somehow need to also enable it on the upstream module so it knows to expect proxy protocol. 

Thanks!

-Rob

**Comment by erankor** [comment]
Hi, you need to enable it - add `proxy_protocol` to the `listen` directive under `stream`, for example - 
```
...
stream {
    server {
        listen 8002 proxy_protocol;

        ts;
        ts_kmp on;...
```
